flowchart TD
  A([Stadium]) --> B[[Subroutine]]
  B --> C[(Cylinder)]
  C --> D((Circle))
  D --> E{Diamond}
  E --> F{{Hexagon}}
  F --> G[/Parallelogram/]
  G --> H[\Parallelogram Alt\]
  H --> I[/Trapezoid\]
  I --> J[\Trapezoid Alt/]
  J --> K>Asymmetric]
