kanban
  Backlog
    id1[Design new landing page]
    id2[Fix login bug]
  todo[To Do]
    id3[Write API tests]
    id4[Update dependencies]
  doing[In Progress]
    id5[Implement auth flow]
  review[Code Review]
    id6[Refactor database layer]
  done[Done]
    id7[Setup CI/CD pipeline]
    id8[Deploy v1.0]
