sankey-beta
  Agricultural waste,Bio-conversion,124.729
  Bio-conversion,Liquid,0.597
  Bio-conversion,Losses,26.862
  Bio-conversion,Solid,280.322
  Bio-conversion,Gas,81.144
  Solid,Over generation / exports,0.001
  Liquid,Industry,121.066
  Gas,Heating and cooling,79.329
